### PR TITLE
FIX connectionInfo updated when connection closes

### LINKED ISSUE #74: connectionInfo is not updated when connection closes
the subscribe method is not catching the disconnect event, when I manually disconnect.

My disconnect code:

```javascript
  const disconnectFromAllDevices = () => {
    return new Promise((resolve, reject) => {
      getGroupInfo()
        .then(() => removeGroup())
        .then(() => {
          console.log('Succesfully disconnected!');
          resolve(null);
        })
        .catch(err => {
          console.error('Something gone wrong. Details: ', err);
          reject(err);
        });
    });
  };

```

### PR DESCRIPTION
**Pull request by viniciuscb**
FIXES #74

### CODE REVIEW

**Comment by kirillzyusko** [comment]
Could you please explain why you've removed if statement?

I copied code from here:

```java
    ...
    } else if (WifiP2pManager.WIFI_P2P_CONNECTION_CHANGED_ACTION.equals(action)) {

        if (manager == null) {
            return;
        }

        NetworkInfo networkInfo = (NetworkInfo) intent
                .getParcelableExtra(WifiP2pManager.EXTRA_NETWORK_INFO);

        if (networkInfo.isConnected()) {

            // We are connected with the other device, request connection
            // info to find group owner IP

            manager.requestConnectionInfo(channel, connectionListener);
        }
        ...
```

Source: https://developer.android.com/training/connect-devices-wirelessly/wifi-direct#connect

**Comment by viniciuscb** [comment]
Yes, this is preventing the user's code to receive an update on connectionInfo when the connection is closed by the other peer. 

After this patch, I started receiving updates when connection is closed. See this log:

```
{"groupFormed": false, "groupOwnerAddress": null, "isGroupOwner": false}
```

with this patch the user can realiably look into connectionInfo.groupFormed to see if the connection with other peers is open or closed.

**Comment by kirillzyusko** [comment]
Okay, looks good 👍 
Could you please fix java-lint/formatting issues?

Just run `node scripts/java-lint.js` and it should automatically resolve all issues

**Comment by viniciuscb** [comment]
linted

**Pull request merged**
