### PR TITLE
Added Missing Imports

### PR DESCRIPTION
**Pull request by guptaamol**
Added Missing Import.

### CODE REVIEW

**Comment by kirillzyusko** [comment]
Hi @guptaamol
Does it mean, that published 3.2.0 is not working because of missed imports? :)

**Comment by guptaamol** [comment]
Yeah im sorry for that...

**Comment by kirillzyusko** [comment]
No problem
Tomorrow I will merge it an publish new version 3.2.1

**Comment by guptaamol** [comment]
I have come across this issue For some reason the native module is not
being registered and when I call initialize on the js side I get an
error message stating the method `init` is being called on a null object
reference. I am using react native version 62.2

**Comment by guptaamol** [comment]
The native module not being imported seemed to be a caching issues and was
resolved after I restarted the packager.

I was able to run the app and after filling in the imports everything was
working fine.

Please merge the pull request everything is working fine now. :)

**Comment by kirillzyusko** [comment]
Published as 3.2.1

**Pull request merged**
